annotations:
- metadata:
    annotation_method: manual labeling.
    annotation_object:
      description: Cytosolic ribosome
      id: GO:0009431
      name: flagellar basal body, MS ring
      state: 96 nm repeat
    annotation_publications: EMPIAR-10988, EMD-14412, EMD-14413, EMD-14415, EMD-14417,
      EMD-14418, EMD-14419, EMD-14420, 10.1101/2022.04.12.488077
    annotation_software: IMOD
    authors:
    - ORCID: 0000-0001-8324-4040
      corresponding_author_status: true
      name: Mohammed Kaplan
      primary_author_status: true
    confidence:
      ground_truth_used: author estimation
      precision: 95
      recall: 90
    dates:
      deposition_date: '2024-05-20'
      last_modified_date: '2024-05-20'
      release_date: '2024-05-20'
    ground_truth_status: false
    is_curator_recommended: true
    method_type: manual
    version: 1.0
  sources:
  - binning: 1
    columns: xyz
    delimiter: ' '
    file_format: mod
    filter_value: '{mapped_tomo_name}.tomostar'
    glob_string: '{dataset_name}/{run_name}_MS.mod'
    is_visualization_default: true
    mask_label: 1
    order: xyz
    shape: OrientedPoint
dataset_keyphotos:
- sources:
  - literal:
      value:
        snapshot: cryoetportal-rawdatasets-dev/GJensen_full/dga2017-07-08-1/keyimg_dga2017-07-08-1.jpg
        thumbnail: cryoetportal-rawdatasets-dev/GJensen_full/dga2017-07-08-1/keyimg_dga2017-07-08-1_s.jpg
datasets:
- metadata:
    authors:
    - ORCID: 0000-0001-8324-4040
      corresponding_author_status: true
      name: Grant Jensen
      primary_author_status: false
    cell_component:
      id: GO:0051301
      name: Outer Mitochondrial Membrane
    cell_strain:
      id: https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=284812
      name: Philadelphia-1_Lp02
    cell_type:
      id: CL:0002618
      name: umbilical vein endothelial cell
    cross_references:
      dataset_publications: doi:10.1101/2022.04.12.488077, doi:10.1038/s41592-022-01746-2
      related_database_entries: EMPIAR-10988, EMD-14412, EMD-14413, EMD-14415, EMD-14417,
        EMD-14418, EMD-14419, EMD-14420
    dataset_description: 'This is 27th of 41 sets of data studying Legionella pneumophila
      collected by Debnath Ghosal and is a part of Caltech Jensen  lab etdb. JV9114:
      DotC-sfGFP fusion to the wild-type gene on the chromosome (thyA).'
    dataset_identifier: 10084
    dataset_title: L. pneumophila JV9114
    dates:
      deposition_date: '2023-10-01'
      last_modified_date: '2023-12-01'
      release_date: '2023-12-01'
    funding:
    - funding_agency_name: European Research Council (ERC)
      grant_id: '760067'
    grid_preparation: "6 grids were frozen for the JV9114 strain (2x concentrated\
      \ culture); Vitrobot (MK iv) settings: 100% humidity, 4\xB5l sample, Blot force\
      \ 6, blot time 4.5 sec. Wait time 0 sec. Drain time 1 sec. Ethane/propane mix.\
      \ Grid: Quantifoil Cu 2/2 200. 3 grids with extra-thick carbon (JV9114T) and\
      \ three finder grids (JV9114F). Add gold to cells prior to freezing: 1ul of\
      \ gold to 4 ul of cells, freeze."
    organism:
      name: Legionella pneumophila
      taxonomy_id: 1080311
    sample_preparation: 'Cells were grown in AYE liquid culture with following supplements:
      ferric nitrate, cysteine hydrochloride and thymidine. Scrape cells off a plate,
      dissolve in the media, adjust the cell density to 0.6 and make a dilution series.
      Start O/N culture with all of them and freeze cells next day from the one in
      early stationary phase that is OD ~ 3.0. This time cell density was 2.8'
    sample_type: organism
  sources:
  - literal:
      value:
      - '10009'
    source_glob:
      list_glob: 100??
      match_regex: .*
      name_regex: (.*)
frames:
- sources:
  - source_glob:
      list_glob: frames/{run_name}_*.tif
gains:
- sources:
  - source_glob:
      list_glob: frames/CountRef.dm4
key_images:
- sources:
  - literal:
      value:
      - from_tomogram
    source_glob:
      list_glob: '{run_name}/keyimg_{run_name}.jpg'
rawtilts:
- sources:
  - source_multi_glob:
      list_globs:
      - Tomo{run_name}/raw_data/imod_metadata/*.tlt
runs:
- sources:
  - source_glob:
      list_glob: '*'
      match_regex: (dga2017-07-08-1|dga2017-07-08-2|dga2017-07-08-3|dga2017-07-08-4|dga2017-07-08-5|dga2017-07-08-6|dga2017-07-08-7|dga2017-07-08-8|dga2017-07-08-9|dga2017-07-08-10|dga2017-07-08-11|dga2017-07-08-13|dga2017-07-08-14|dga2017-07-08-15|dga2017-07-08-16|dga2017-07-08-17|dga2017-07-08-18|dga2017-07-08-19|dga2017-07-08-20|dga2017-07-08-21|dga2017-07-08-22|dga2017-07-08-23|dga2017-07-08-24|dga2017-07-08-25|dga2017-07-08-26|dga2017-07-08-27|dga2017-07-08-28|dga2017-07-08-29|dga2017-07-08-30|dga2017-07-08-31|dga2017-07-08-32|dga2017-07-08-33|dga2017-07-08-34|dga2017-07-08-35|dga2017-07-08-36|dga2017-07-08-37|dga2017-07-08-38|dga2017-07-08-39|dga2017-07-08-40|dga2017-07-08-41|dga2017-07-08-42|dga2017-07-08-43|dga2017-07-08-44|dga2017-07-08-45|dga2017-07-08-46|dga2017-07-08-47|dga2017-07-08-48|dga2017-07-08-49|dga2017-07-08-50|dga2017-07-08-51|dga2017-07-08-52|dga2017-07-08-53|dga2017-07-08-54|dga2017-07-08-55|dga2017-07-08-56|dga2017-07-08-57|dga2017-07-08-58|dga2017-07-08-59|dga2017-07-08-60|dga2017-07-08-61|dga2017-07-08-62|dga2017-07-08-63|dga2017-07-08-64|dga2017-07-08-65|dga2017-07-08-66|dga2017-07-08-67|dga2017-07-08-68|dga2017-07-08-69|dga2017-07-08-70|dga2017-07-08-71|dga2017-07-08-72|dga2017-07-08-73|dga2017-07-08-74|dga2017-07-08-75|dga2017-07-08-76|dga2017-07-08-77|dga2017-07-08-78|dga2017-07-08-79|dga2017-07-08-80|dga2017-07-08-81|dga2017-07-08-82|dga2017-07-08-83|dga2017-07-08-84|dga2017-07-08-85|dga2017-07-08-86|dga2017-07-08-87|dga2017-07-08-88|dga2017-07-08-89|dga2017-07-08-90|dga2017-07-08-91|dga2017-07-08-92|dga2017-07-08-93|dga2017-07-08-94|dga2017-07-08-95|dga2017-07-08-96|dga2017-07-08-97|dga2017-07-08-98|dga2017-07-08-99|dga2017-07-08-100|dga2017-07-08-101|dga2017-07-08-102|dga2017-07-08-103|dga2017-07-08-104|dga2017-07-08-105)$
      name_regex: (.*)
standardization_config:
  deposition_id: 10084
  run_data_map_file: run_data_map/10084.csv
  run_to_frame_map_csv: run_frames_map/10084.csv
  run_to_tomo_map_csv: run_tomo_map/10084.csv
  run_to_ts_map_csv: tomo_ts_map.csv
  source_prefix: GJensen_full
tiltseries:
- metadata:
    acceleration_voltage: 300000
    aligned_tiltseries_binning: 1
    binning_from_frames:
    - 1
    - REQUIRED
    - 14.08
    camera:
      acquire_mode: counting
      manufacturer: Gatan
      model: K2
    data_acquisition_software: UCSFTomo
    is_aligned: false
    microscope:
      additional_scope_info: ''
      manufacturer: TFS
      model: Krios
    microscope_optical_setup:
      energy_filter: GIF
      phase_plate:
      - false
      - None
    pixel_spacing:
    - '{run_pixel_spacing}'
    - 1.96
    related_empiar_entry: EMPIAR-10988
    spherical_aberration_constant:
    - '{ts-spherical_aberration_constant}'
    - 2.0
    tilt_alignment_software: '{ts-tilt_alignment_software}'
    tilt_axis:
    - float {tilt_series_tilt_axis_angle}
    - 6.4
    - 79
    tilt_range:
      max:
      - float {tilt_series_max_tilt}
      - 40
      - 65.0
      min:
      - float {tilt_series_min_tilt}
      - -60
      - -65.0
    tilt_series_path: '{ts-tilt_series_path}'
    tilt_series_quality:
    - int {tilt_series_quality}
    - 5
    tilt_step:
    - 3
    - 2.0
    - float {ts-tilt_step}
    tilting_scheme: starting tilt to max then min
    total_flux:
    - float {tilt_series_total_flux}
    - 100
    - 143.5
  sources:
  - parent_filters:
      exclude:
        run:
        - ^14$
      include:
        run:
        - ^11$
    source_glob:
      list_glob: '{run_name}/rawdata/*'
      match_regex: .*/rawdata/[^\._].*\.(mrc|st|ali)$
      name_regex: (.*)
tomograms:
- metadata:
    affine_transformation_matrix:
    - - 1
      - 0
      - 0
      - 0
    align_software: '{tomo-align_softwares}'
    authors:
    - ORCID: 0000-0001-8324-4040
      corresponding_author_status: true
      name: Grant Jensen
      primary_author_status: false
    ctf_corrected: true
    fiducial_alignment_status: FIDUCIAL
    offset:
      x: 0
      y: 0
      z: 0
    processing: raw
    processing_software: '{tomo-processing_software}'
    reconstruction_method: '{tomo-reconstruction_method}'
    reconstruction_software: '{tomo-reconstruction_software}'
    tomogram_version: 1
    voxel_spacing:
    - '{run_voxel_spacing}'
    - 7.84
  sources:
  - source_glob:
      list_glob: '{run_name}/{mapped_tomo_name}'
      match_regex: .*\.(mrc|rec)$
voxel_spacings:
- sources:
  - destination_glob:
      list_glob: '{run_output_path}/Tomograms/VoxelSpacing*'
      match_regex: .*
      name_regex: VoxelSpacing(.*)
    literal:
      value:
      - 13.68
      - float {run_voxel_spacing}
